### ISSUE TITLE
[BUG]: Error when rerunning the app after 1 sucessful completion

### ISSUE THREAD

**Issue by daavoo** [mozilla-ai/document-to-podcast#57]
### Description

After a succesful completion and having downloaded the result, clicking again on Generate Podcast crashes the app.
This seems to have been introduced in https://github.com/mozilla-ai/document-to-podcast/pull/42

### Reproduction

1. Run the app successfully once
2. Make some modification (i.e. update the prompt)
3. Run `Generate Podcast Script` again.

### Relevant log output

```shell
`
Traceback (most recent call last):
  File "/usr/local/python/3.10.16/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
  File "/usr/local/python/3.10.16/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
  File "/workspaces/document-to-podcast/demo/app.py", line 154, in <module>
    st.session_state.audio.append(speech)
AttributeError: 'numpy.ndarray' object has no attribute 'append'
```

### Expected behavior

I would expect to generate a new podcast script

### System Info

- default codespaces

### Have you searched for similar issues before submitting this one?

- [x] Yes, I have searched for similar issues
